const assert = require('node:assert/strict')
const { detectIntent, INTENTS } = require('../src/services/intentService')
const { unknownReply, clarifyLowConfidence, HELP_TEXT, WELCOME_TEXT } = require('../src/utils/uxMessages')

assert.match(WELCOME_TEXT, /bank statement/i)
assert.match(WELCOME_TEXT, /Upload a bank statement/i)
assert.doesNotMatch(WELCOME_TEXT, /Show subscriptions/)
assert.match(unknownReply('blah'), /help/)
assert.match(unknownReply('delete'), /Delete something/)
assert.ok(clarifyLowConfidence(INTENTS.REMINDER_CREATE))
assert.equal(detectIntent('Delete').intent, INTENTS.SUBSCRIPTION_DELETE)
assert.equal(detectIntent('dont let me forget to pay rent').intent, INTENTS.REMINDER_CREATE)
assert.equal(detectIntent('netflix 149 every month').intent, INTENTS.SUBSCRIPTION_CREATE)

console.log('UX tests passed: 8')
